# Generated by Django 4.1.2 on 2022-10-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.IntegerField(unique=True)),
                ('itemName', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
