# Generated by Django 4.1.2 on 2022-11-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
