# Generated by Django 4.1.3 on 2023-01-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_transaction_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkOrderNo', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('workOrder', models.ManyToManyField(to='inventory.workorder')),
            ],
            options={
                'ordering': ['quantity'],
            },
        ),
    ]
