# Generated by Django 4.1.3 on 2023-01-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_workorder_workorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='itemId',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
