# Generated by Django 4.1.2 on 2023-01-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_workorderitem_itemid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderitem',
            name='workOrder',
        ),
        migrations.AddField(
            model_name='transaction',
            name='billNumber',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
        migrations.DeleteModel(
            name='WorkOrderItem',
        ),
    ]
