# Generated by Django 4.1.3 on 2023-01-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_transaction_vendor_alter_transaction_billnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='billNumber',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issuee',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField(default='00:00')),
                ('vendor', models.CharField(max_length=1000)),
                ('billNumber', models.CharField(max_length=1000)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
    ]
