# Generated by Django 4.1.3 on 2023-01-19 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_transaction_billnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkOrderNo', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default='00:00')),
                ('issuee', models.CharField(max_length=1000)),
                ('items', models.CharField(max_length=1000)),
            ],
        ),
    ]
