# Generated by Django 4.1.3 on 2023-01-19 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='completeionDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='items',
            field=models.TextField(),
        ),
    ]
