# Generated by Django 4.1.3 on 2023-01-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_workorder_completed_workorder_completeiondate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='completeionDate',
            new_name='completionDate',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='WorkOrderNo',
            new_name='workOrderNo',
        ),
    ]
