# Generated by Django 4.1.3 on 2023-02-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_transaction_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='itemName',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
